[package]
name = "disk-mpmc"
version = "0.1.0"
edition = "2021"

[dependencies]
atomic-wait = "1.1.0"
mmapcell = "0.1.2"
parking_lot = "0.12.3"
tracing = "0.1.40"

[dev-dependencies]
rand = "0.8.5"
tracing-subscriber = "0.3.18"
